version: '3.8'

services:
  mysql-db:
    image: library/mysql:5.7.24
    container_name: mural-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha01
      MYSQL_DATABASE: mural
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
  app:
    image: adrianopc/mural_api:v1
    container_name: mural_app
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mural
      HABILITAR_CARREGAR_MASSA_DADOS: 'false'
    ports:
      - "9090:8080"  # host:container
